# Generated by Django 2.1 on 2018-09-11 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Chapter Name')),
                ('chapter_desc', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Chapter Description')),
                ('includes', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Includes')),
                ('useAdditionalCode', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Use Additional Codes')),
                ('excludes1', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Excludes 1')),
                ('excludes2', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Excludes 2')),
                ('sectionIndex', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Section Index')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diag_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Diagnosis Name')),
                ('diag_code', models.TextField(blank=True, max_length=200, null=True, verbose_name='Diagnosis Code')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Section ID')),
                ('diag_id', models.TextField(blank=True, max_length=200, null=True, verbose_name='Diagnosis ID')),
                ('desc', models.TextField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('chapter_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icd10.Chapter')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='section_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icd10.Section'),
        ),
    ]
