# Generated by Django 2.1 on 2018-09-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FDADrugs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Drug Name')),
                ('dosage', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Dosage')),
                ('form', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Form')),
                ('active_ingredient', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Active Ingredient')),
            ],
            options={
                'verbose_name': 'FDA Drugs',
                'verbose_name_plural': 'FDA Drugs',
                'ordering': ['drug_name', 'active_ingredient', 'dosage', 'form'],
            },
        ),
    ]
