# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-25 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_hospital_id', models.CharField(max_length=15, unique=True, verbose_name='Hospital ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, help_text='Please enter Initials / Middle Name', max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, help_text='Enter Initials / Last Name', max_length=30, null=True)),
                ('full_name', models.CharField(editable=False, max_length=100)),
                ('age', models.CharField(blank=True, max_length=10, null=True)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=6)),
                ('parent_clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.Clinic')),
            ],
            options={
                'verbose_name': 'Patient - Basic Data',
                'verbose_name_plural': 'Patient - Basic Data',
                'ordering': ('first_name', 'middle_name', 'last_name', 'age', 'sex', 'patient_hospital_id'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='patientdetail',
            unique_together=set([('patient_hospital_id', 'parent_clinic')]),
        ),
    ]
