# Generated by Django 4.2.26 on 2025-11-07 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "smoking_status",
                    models.CharField(
                        choices=[
                            ("never", "Never Smoked"),
                            ("former", "Former Smoker"),
                            ("current", "Current Smoker"),
                        ],
                        default="never",
                        max_length=20,
                    ),
                ),
                (
                    "smoking_details",
                    models.TextField(
                        blank=True,
                        help_text="Details about smoking (packs per day, years smoked, quit date, etc.)",
                        null=True,
                    ),
                ),
                (
                    "alcohol_use",
                    models.CharField(
                        choices=[
                            ("none", "No Alcohol Use"),
                            ("occasional", "Occasional"),
                            ("moderate", "Moderate"),
                            ("heavy", "Heavy"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "alcohol_details",
                    models.TextField(
                        blank=True,
                        help_text="Details about alcohol use (drinks per week, type, etc.)",
                        null=True,
                    ),
                ),
                (
                    "drug_use",
                    models.CharField(
                        choices=[
                            ("none", "No Drug Use"),
                            ("former", "Former User"),
                            ("current", "Current User"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "drug_details",
                    models.TextField(
                        blank=True, help_text="Details about drug use", null=True
                    ),
                ),
                (
                    "exercise_frequency",
                    models.CharField(
                        blank=True,
                        help_text="Exercise frequency (e.g., 3 times per week)",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("occupation", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "occupational_hazards",
                    models.TextField(
                        blank=True,
                        help_text="Any occupational hazards or exposures",
                        null=True,
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("single", "Single"),
                            ("married", "Married"),
                            ("divorced", "Divorced"),
                            ("widowed", "Widowed"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "living_situation",
                    models.CharField(
                        blank=True,
                        help_text="Living situation (lives alone, with family, etc.)",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional social history notes",
                        null=True,
                    ),
                ),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_history",
                        to="patient.patientdetail",
                    ),
                ),
            ],
            options={
                "verbose_name": "Social History",
                "verbose_name_plural": "Social History",
            },
        ),
        migrations.CreateModel(
            name="PastMedicalHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("illness", "Illness/Disease"),
                            ("surgery", "Surgery/Procedure"),
                            ("injury", "Injury/Trauma"),
                            ("hospitalization", "Hospitalization"),
                            ("other", "Other"),
                        ],
                        default="illness",
                        help_text="Type of medical condition",
                        max_length=20,
                    ),
                ),
                (
                    "condition_name",
                    models.CharField(
                        help_text="Name of the condition, surgery, or procedure",
                        max_length=200,
                    ),
                ),
                (
                    "icd_code",
                    models.CharField(
                        blank=True,
                        help_text="ICD-10 code if applicable",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "date_diagnosed",
                    models.DateField(
                        blank=True,
                        help_text="Date when condition was diagnosed or procedure was performed",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("resolved", "Resolved"),
                            ("chronic", "Chronic"),
                        ],
                        default="resolved",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the condition",
                        null=True,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="past_medical_history",
                        to="patient.patientdetail",
                    ),
                ),
            ],
            options={
                "verbose_name": "Past Medical History",
                "verbose_name_plural": "Past Medical History",
                "ordering": ["-date_diagnosed"],
            },
        ),
        migrations.CreateModel(
            name="FamilyHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("father", "Father"),
                            ("mother", "Mother"),
                            ("brother", "Brother"),
                            ("sister", "Sister"),
                            ("grandfather_paternal", "Grandfather (Paternal)"),
                            ("grandmother_paternal", "Grandmother (Paternal)"),
                            ("grandfather_maternal", "Grandfather (Maternal)"),
                            ("grandmother_maternal", "Grandmother (Maternal)"),
                            ("uncle", "Uncle"),
                            ("aunt", "Aunt"),
                            ("child", "Child"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "condition",
                    models.CharField(help_text="Medical condition", max_length=200),
                ),
                (
                    "age_of_onset",
                    models.CharField(
                        blank=True,
                        help_text="Age when condition developed",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes", null=True
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_history",
                        to="patient.patientdetail",
                    ),
                ),
            ],
            options={
                "verbose_name": "Family History",
                "verbose_name_plural": "Family History",
                "ordering": ["relationship"],
            },
        ),
        migrations.CreateModel(
            name="CurrentMedication",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "medication_name",
                    models.CharField(
                        help_text="Name of the medication", max_length=200
                    ),
                ),
                (
                    "dosage",
                    models.CharField(
                        help_text="Dosage (e.g., 500mg, 10ml)", max_length=100
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        help_text="Frequency (e.g., twice daily, once a week)",
                        max_length=100,
                    ),
                ),
                (
                    "route",
                    models.CharField(
                        choices=[
                            ("oral", "Oral"),
                            ("iv", "Intravenous"),
                            ("im", "Intramuscular"),
                            ("topical", "Topical"),
                            ("inhaled", "Inhaled"),
                            ("other", "Other"),
                        ],
                        default="oral",
                        max_length=50,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, help_text="Date medication was started", null=True
                    ),
                ),
                (
                    "prescribed_by",
                    models.CharField(
                        blank=True,
                        help_text="Name of prescribing physician",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "indication",
                    models.CharField(
                        blank=True,
                        help_text="Reason for taking this medication",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes", null=True
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="current_medications",
                        to="patient.patientdetail",
                    ),
                ),
            ],
            options={
                "verbose_name": "Current Medication",
                "verbose_name_plural": "Current Medications",
                "ordering": ["medication_name"],
            },
        ),
        migrations.CreateModel(
            name="Allergy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allergy_type",
                    models.CharField(
                        choices=[
                            ("drug", "Drug/Medication"),
                            ("food", "Food"),
                            ("environmental", "Environmental"),
                            ("other", "Other"),
                        ],
                        default="drug",
                        max_length=20,
                    ),
                ),
                (
                    "allergen",
                    models.CharField(help_text="Name of the allergen", max_length=200),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("mild", "Mild"),
                            ("moderate", "Moderate"),
                            ("severe", "Severe"),
                            ("life_threatening", "Life Threatening"),
                        ],
                        default="mild",
                        max_length=20,
                    ),
                ),
                (
                    "reaction",
                    models.TextField(help_text="Description of the allergic reaction"),
                ),
                (
                    "date_identified",
                    models.DateField(
                        blank=True,
                        help_text="Date when allergy was identified",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes", null=True
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allergies",
                        to="patient.patientdetail",
                    ),
                ),
            ],
            options={
                "verbose_name": "Allergy",
                "verbose_name_plural": "Allergies",
                "ordering": ["-severity", "allergen"],
            },
        ),
    ]
