# Generated by Django 4.2.26 on 2025-11-10 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("patient", "0002_socialhistory_pastmedicalhistory_familyhistory_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientModule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Module name (e.g., 'Medical History', 'Immunizations')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Display name shown in UI", max_length=100
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="📋",
                        help_text="Emoji or icon for the module",
                        max_length=10,
                    ),
                ),
                (
                    "url_pattern",
                    models.CharField(
                        help_text="URL pattern with {patient_id} placeholder",
                        max_length=200,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("clinical", "Clinical"),
                            ("diagnostic", "Diagnostic"),
                            ("screening", "Screening"),
                            ("administrative", "Administrative"),
                            ("other", "Other"),
                        ],
                        default="clinical",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Module description"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this module available?"
                    ),
                ),
                (
                    "requires_privilege",
                    models.CharField(
                        blank=True,
                        help_text="Required user privilege/permission",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0, help_text="Display order (lower numbers first)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Module",
                "verbose_name_plural": "Patient Modules",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ModuleAssignmentRule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("age_range", "Age Range"),
                            ("sex", "Sex"),
                            ("diagnosis", "Diagnosis (ICD Code)"),
                            ("tag", "Patient Tag"),
                            ("procedure", "Procedure Done"),
                            ("doctor", "Specific Doctor"),
                            ("patient", "Specific Patient"),
                            ("global", "Global (All Patients)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="Higher priority rules checked first"
                    ),
                ),
                (
                    "min_age",
                    models.IntegerField(
                        blank=True, help_text="Minimum age for this rule", null=True
                    ),
                ),
                (
                    "max_age",
                    models.IntegerField(
                        blank=True, help_text="Maximum age for this rule", null=True
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Others", "Others"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "icd_codes",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated ICD-10 codes (e.g., E11.9, I10)",
                        null=True,
                    ),
                ),
                (
                    "patient_tags",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated tags (e.g., diabetic, hypertensive)",
                        null=True,
                    ),
                ),
                (
                    "procedure_codes",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated procedure codes",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of this rule"),
                ),
                (
                    "assigned_doctor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Module available only for this doctor's patients",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_patient",
                    models.ForeignKey(
                        blank=True,
                        help_text="Module assigned to specific patient",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specific_module_assignments",
                        to="patient.patientdetail",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment_rules",
                        to="patient.patientmodule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Module Assignment Rule",
                "verbose_name_plural": "Module Assignment Rules",
                "ordering": ["-priority", "rule_type"],
            },
        ),
        migrations.CreateModel(
            name="PatientTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(help_text="Tag name", max_length=50)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about this tag"
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patient_tags_added",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="patient.patientdetail",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Tag",
                "verbose_name_plural": "Patient Tags",
                "unique_together": {("patient", "tag")},
            },
        ),
    ]
