# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-25 14:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuShadhaUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aushadha_user_role', models.CharField(choices=[('audhadha_admin', 'AuShadha Admin'), ('aushadha_user', 'AuShadha User'), ('aushadha_staff', 'AuShadha Staff '), ('aushadha_developer', 'AuShadha Developer')], default='aushadha_user', help_text=' Users Role in AuShadha Software.\n                               This is different from the role in the Clinic\n                               ', max_length=30, verbose_name='AuShadha User Role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
