# Generated by Django 2.1 on 2018-09-10 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aushadha_users', '0002_auto_20170407_0518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aushadhauser',
            options={'verbose_name': 'AuShadha User', 'verbose_name_plural': 'AuShadha User'},
        ),
    ]
