# Generated by Django 2.1 on 2018-09-11 05:59

from django.db import migrations, models
import django.db.models.deletion
import registry.icd10pcs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppCfg',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cfg_key', models.CharField(max_length=100)),
                ('cfg_value', models.CharField(max_length=100)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Approach',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('codepage', models.CharField(max_length=3)),
                ('code', models.CharField(max_length=1)),
                ('row_num', models.PositiveIntegerField()),
                ('pos', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['codepage', 'row_num', 'pos', 'code'],
                'abstract': False,
            },
            bases=(models.Model, registry.icd10pcs.models.TableAxisLabelMixin),
        ),
        migrations.CreateModel(
            name='AppTxt',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('txt', models.CharField(max_length=1000)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BodyPart',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('codepage', models.CharField(max_length=3)),
                ('code', models.CharField(max_length=1)),
                ('row_num', models.PositiveIntegerField()),
                ('pos', models.PositiveIntegerField()),
                ('label_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='icd10pcs.AppTxt')),
            ],
            options={
                'ordering': ['codepage', 'row_num', 'pos', 'code'],
                'abstract': False,
            },
            bases=(models.Model, registry.icd10pcs.models.TableAxisLabelMixin),
        ),
        migrations.CreateModel(
            name='BodySystem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('codepage', models.CharField(max_length=3)),
                ('code', models.CharField(max_length=1)),
                ('label_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='icd10pcs.AppTxt')),
                ('title_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='icd10pcs.AppTxt')),
            ],
            options={
                'ordering': ['codepage', 'code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CodePageRow',
            fields=[
                ('id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('codepage', models.CharField(max_length=3)),
                ('row_num', models.IntegerField()),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('codepage', models.CharField(max_length=3)),
                ('code', models.CharField(max_length=1)),
                ('row_num', models.PositiveIntegerField()),
                ('pos', models.PositiveIntegerField()),
                ('label_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='icd10pcs.AppTxt')),
                ('row_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icd10pcs.CodePageRow')),
                ('title_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='icd10pcs.AppTxt')),
            ],
            options={
                'ordering': ['codepage', 'row_num', 'pos', 'code'],
                'abstract': False,
            },
            bases=(models.Model, registry.icd10pcs.models.TableAxisLabelMixin),
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('codepage', models.CharField(max_length=3)),
                ('code', models.CharField(max_length=1)),
                ('defn_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='icd10pcs.AppTxt')),
                ('label_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='icd10pcs.AppTxt')),
                ('title_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='icd10pcs.AppTxt')),
            ],
            options={
                'ordering': ['codepage', 'code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Qualifier',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('codepage', models.CharField(max_length=3)),
                ('code', models.CharField(max_length=1)),
                ('row_num', models.PositiveIntegerField()),
                ('pos', models.PositiveIntegerField()),
                ('label_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='icd10pcs.AppTxt')),
                ('row_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icd10pcs.CodePageRow')),
                ('title_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='icd10pcs.AppTxt')),
            ],
            options={
                'ordering': ['codepage', 'row_num', 'pos', 'code'],
                'abstract': False,
            },
            bases=(models.Model, registry.icd10pcs.models.TableAxisLabelMixin),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('codepage', models.CharField(max_length=3)),
                ('code', models.CharField(max_length=1)),
                ('label_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='icd10pcs.AppTxt')),
                ('title_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='icd10pcs.AppTxt')),
            ],
            options={
                'ordering': ['codepage', 'code'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bodypart',
            name='row_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icd10pcs.CodePageRow'),
        ),
        migrations.AddField(
            model_name='bodypart',
            name='title_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='icd10pcs.AppTxt'),
        ),
        migrations.AddField(
            model_name='approach',
            name='label_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='icd10pcs.AppTxt'),
        ),
        migrations.AddField(
            model_name='approach',
            name='row_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icd10pcs.CodePageRow'),
        ),
        migrations.AddField(
            model_name='approach',
            name='title_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='icd10pcs.AppTxt'),
        ),
    ]
