# Generated by Django 2.1 on 2018-09-11 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineCVXToMVX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.TextField(max_length=500)),
                ('mvx_code', models.CharField(max_length=50)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('product_name_status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=50, null=True)),
                ('mvx_status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=50, null=True)),
                ('cdc_product_name', models.TextField(blank=True, max_length=100, null=True)),
                ('manufacturer', models.TextField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VaccineData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=30)),
                ('field_value', models.TextField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VaccineDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_id', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VaccineRegistry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('lot_number', models.CharField(max_length=100)),
                ('manufacturing_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('vis', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Vaccine Information Statement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='vaccinedata',
            name='vaccine_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccine_registry.VaccineDetail'),
        ),
        migrations.AddField(
            model_name='vaccinecvxtomvx',
            name='cvxcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccine_registry.VaccineDetail'),
        ),
    ]
