# Generated by Django 2.1 on 2018-09-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_for', models.CharField(choices=[('patient', 'Patient'), ('admission', 'Admission'), ('visit', 'Visit'), ('phone_number', 'Phone Number'), ('address', 'Address'), ('city', 'City')], default='patient', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
